#!/bin/bash
mkdir -p database/
mkdir -p artefacts/

rm -rf database/*
rm -rf artefacts/*

java -jar binaries/inspect.jar --keep-artefacts -w artefacts/ -d -i $1
souffle souffle_logic/main.dl -F artefacts/* -D database/

echo -e "\nRequire Auth Violation: "
cat database/AuthViolation.csv

# echo -e "\nDB Insn: "
# cat database/DBInsn.csv

echo -e "\nRollback Violation: "
cat database/RollbackViolation.csv

echo -e "\nFake Token Violation: "
cat database/FakeTokenViolation.csv

echo -e "\nSeperation Violation: "
cat database/SeperationViolation.csv

echo -e "\nFake Notification Violation: "
cat database/FakeNotifyViolation.csv

echo -e "\nNumeric Overflow Violation: "
cat database/OverflowViolation.csv
