#!/usr/bin/env python3
import csv
import os

# print out the decompiled program according to "follows.fact"
facts = os.getcwd() + "/artefacts"
fact = os.listdir(facts)[0]

instr = dict()
with open(facts + "/" + fact + '/must/follows.facts', newline='') as csvfile:
	reader = csv.reader(csvfile, delimiter='\t')
	for row in reader:
		instr[row[0]] = row[1]

start = []
for key in instr:
	if key not in instr.values():
		start.append(key)

program = []
for key in start:
	mod = "1: " + key
	i = 2
	keys = set()
	while key in instr:
		mod += "\n" + str(i) + ": "+ instr[key]
		if key in keys: break
		keys.add(key)
		key = instr[key]
		i += 1
	program.append(mod)

print("\n\n".join(program))
